/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import Courses.Course;
import JSON.CourseService;
import JSON.StudentService;
import Users.Student;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class BrowseEnrollCourses extends javax.swing.JFrame {

    /**
     * Creates new form BrowseEnrollCourses
     */
  private Student student;
    private StudentService studentService;
    private CourseService courseService;

    public BrowseEnrollCourses(Student student, StudentService studentService, CourseService courseService) {
        this.student = student;
        this.studentService = studentService;
        this.courseService = courseService;

        initComponents();
        setupTable();
    }

  private void setupTable() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Course ID", "Title"}, 0
        );
        coursesTable.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        myCoursesBtn = new javax.swing.JButton();
        enrollBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        browseBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(coursesTable);

        myCoursesBtn.setText("view my enrolled courses");
        myCoursesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCoursesBtnActionPerformed(evt);
            }
        });

        enrollBtn.setText("Enroll");
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        browseBtn1.setText("Browse");
        browseBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(enrollBtn)
                .addGap(18, 18, 18)
                .addComponent(browseBtn1)
                .addGap(18, 18, 18)
                .addComponent(myCoursesBtn)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollBtn)
                    .addComponent(backBtn)
                    .addComponent(browseBtn1)
                    .addComponent(myCoursesBtn))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myCoursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCoursesBtnActionPerformed
        List<Course> list = courseService.getEnrolledCourses(student.getUserID());
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(this, "You are not enrolled");
            System.out.println("empty");
            return;
        }
        EnrolledOnlyCoursesFrame e =  new EnrolledOnlyCoursesFrame(student, studentService, courseService);
        e.setVisible(true);
        e.setLocationRelativeTo(null);

    this.dispose();
    }//GEN-LAST:event_myCoursesBtnActionPerformed

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBtnActionPerformed
        // TODO add your handling code here
        int row = coursesTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course.");
            return;
        }

        String courseId = coursesTable.getValueAt(row, 0).toString();
        boolean studentEnrolled =  courseService.enrollStudent(courseId,student.getUserID());

        boolean ok = student.enrollCourse(courseId);

        if (studentEnrolled) {
            studentService.enrollStudentInCourse(student, courseId); // <--- ENSURE SAVE
            JOptionPane.showMessageDialog(this, "Enrolled successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Already enrolled.");
        }//GEN-LAST:event_enrollBtnActionPerformed
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        SignInApp.studentDashboard(student);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void browseBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtn1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) coursesTable.getModel();
        model.setRowCount(0);

        List<Course> courses = studentService.browseCourses();

        if (courses == null || courses.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No courses available.");
            return;
        }

        for (Course c : courses) {
            System.out.println(c.getCourseId());
            if(c.getStatus().equals("accepted")){
                model.addRow(new Object[]{
                        c.getCourseId(),
                        c.getTitle()
                });
            }

        }

    }//GEN-LAST:event_browseBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton browseBtn1;
    private javax.swing.JTable coursesTable;
    private javax.swing.JButton enrollBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton myCoursesBtn;
    // End of variables declaration//GEN-END:variables
}
