/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import Courses.Course;
import JSON.CourseService;
import JSON.StudentService;
import Users.Student;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class EnrolledOnlyCoursesFrame extends javax.swing.JFrame {
private Student student;
    private StudentService studentService;
    private CourseService courseService;

    public EnrolledOnlyCoursesFrame(Student student, StudentService studentService, CourseService courseService) {
        this.student = student;
        this.studentService = studentService;
        this.courseService = courseService;

        initComponents();
        setupTable();
        loadEnrolledCourses();
    }
    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Course ID", "Title"}, 0
        );
        enrolledTable.setModel(model);
    }

    private void loadEnrolledCourses() {
        DefaultTableModel model = (DefaultTableModel) enrolledTable.getModel();
        model.setRowCount(0);

        List<Course> list = courseService.getEnrolledCourses(student.getUserID());

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "You are not enrolled in any course.");
            return;
        }

        for (Course c : list) {
            model.addRow(new Object[]{c.getCourseId(), c.getTitle()});
        }
    }
    /**
     * Creates new form EnrolledOnlyCoursesFrame
     */
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enrolledTable = new javax.swing.JTable();
        viewLessonsBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enrolledTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(enrolledTable);

        viewLessonsBtn.setText("view lessons");
        viewLessonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLessonsBtnActionPerformed(evt);
            }
        });

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewLessonsBtn)
                .addGap(95, 95, 95))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(320, Short.MAX_VALUE)
                    .addComponent(backBtn1)
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(viewLessonsBtn)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(272, Short.MAX_VALUE)
                    .addComponent(backBtn1)
                    .addGap(5, 5, 5)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewLessonsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLessonsBtnActionPerformed
        // TODO add your handling code here:
        int row = enrolledTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

   
    String courseId = enrolledTable.getValueAt(row, 0).toString();
        JFrame frame = new JFrame("Lesson Management");
        LessonManagement lessonPanel = new LessonManagement(student, studentService, courseService, courseId);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(lessonPanel);
        frame.pack(); // sizes the frame to fit the panel
        frame.setLocationRelativeTo(null); // center on screen
        frame.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_viewLessonsBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
      BrowseEnrollCourses b =  new BrowseEnrollCourses(student, studentService, courseService);
      b.setVisible(true);
      b.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_backBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JTable enrolledTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewLessonsBtn;
    // End of variables declaration//GEN-END:variables
}
