/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;
import Courses.Course;
import Courses.Lesson;
import JSON.CourseService;
import JSON.StudentService;
import Users.Student;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mega Store
 */
public class LessonManagement extends javax.swing.JPanel {

    /**
     * Creates new form LessonManagement
     */
    private Student student;
private StudentService studentService;
private CourseService courseService;
private String courseId;

public LessonManagement(Student student, StudentService studentService, CourseService courseService, String courseId) {
    this.student = student;
    this.studentService = studentService;
    this.courseService = courseService;
    this.courseId = courseId;

    initComponents();
    setupTable();
    loadLessons();
}

private void setupTable() {
    DefaultTableModel model = new DefaultTableModel(
            new String[]{"Lesson ID", "Title", "Completed"}, 0
    );
    lessonsTable.setModel(model);
}
    private void loadLessons() {
        DefaultTableModel model = (DefaultTableModel) lessonsTable.getModel();
        model.setRowCount(0);

        List<Lesson> lessons = studentService.getLessonsForCourse(courseId);
        List<String> completed = student.getProgress().getOrDefault(courseId, new ArrayList<>());

        for (Lesson l : lessons) {
            boolean isCompleted = completed.contains(l.getLessonId());

            model.addRow(new Object[]{
                            l.getLessonId(),
                            l.getTitle(),
                            isCompleted ? "Yes" : "No"
                    });
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        markCompletedBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        markCompletedBtn.setText("view completed lessons");
        markCompletedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markCompletedBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markCompletedBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(markCompletedBtn)
                .addGap(15, 15, 15)
                .addComponent(backBtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
       EnrolledOnlyCoursesFrame e =      new EnrolledOnlyCoursesFrame(student, studentService, courseService);
       e.setVisible(true);
       e.setLocationRelativeTo(null);
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void markCompletedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markCompletedBtnActionPerformed
        // TODO add your handling code here:
         int row = lessonsTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson.");
        return;
    }

    String lessonId = lessonsTable.getValueAt(row, 0).toString();

    boolean ok = student.markLessonCompleted(courseId, lessonId);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Lesson marked completed!");
        loadLessons(); // refresh display
    } else {
        JOptionPane.showMessageDialog(this, "Already completed.");
    }
    }//GEN-LAST:event_markCompletedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JButton markCompletedBtn;
    // End of variables declaration//GEN-END:variables
}
