/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import Courses.Lesson;
import static FrontEnd.SignInApp.studentService;
import JSON.InstructorManagment;
import Users.Instructor;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author HP
 */
public class ManageLesson extends javax.swing.JFrame {
private InstructorManagment instructorManagment;
    private Instructor instructor;
    private String courseId;

    private javax.swing.JComboBox<String> jComboBoxLessons; // comboBox for lesson selection
   
    public ManageLesson(InstructorManagment instructorManagment, Instructor instructor, String courseId) {
        this.instructorManagment = instructorManagment;
        this.instructor = instructor;
        this.courseId = courseId;
  jComboBoxLessons = new javax.swing.JComboBox<>();
jComboBoxLessons.setFont(new java.awt.Font("Dialog", 0, 14));
getContentPane().add(jComboBoxLessons); 
        initComponents();
        lessonList(); // populate lessons list
        populateComboBox(); // populate lessons in comboBox
       
    }

    public void lessonList() {
        DefaultListModel<String> model = new DefaultListModel<>();
        List<Lesson> lessons = instructorManagment.getCourseService().getLessons(courseId);
        for (Lesson lesson : lessons) {
            model.addElement(lesson.getLessonId());
        }
        jList1.setModel(model);
    }

    private void populateComboBox() {
        jComboBoxLessons.removeAllItems();
        List<Lesson> lessons = instructorManagment.getCourseService().getLessons(courseId);
        for (Lesson lesson : lessons) {
            jComboBoxLessons.addItem(lesson.getLessonId() + " - " + lesson.getTitle());
        }
    }
    /**
     * Creates new form ManageLesson
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        button4 = new java.awt.Button();
        quizAverageBtn = new java.awt.Button();
        button6 = new java.awt.Button();
        button3 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("Manage Lessons");

        button1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        button1.setLabel("Create Lesson");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        button2.setLabel("Edit Lesson");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        scrollPane1.add(jScrollPane1);

        button4.setLabel("back");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        quizAverageBtn.setActionCommand("View Average");
        quizAverageBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quizAverageBtn.setLabel("Quiz Average");
        quizAverageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizAverageBtnActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        button6.setLabel("Delete Lesson");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        button3.setLabel("Create Quiz");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizAverageBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizAverageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        InstructorDashboard d=new InstructorDashboard(instructorManagment,instructor);
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_button4ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       //
        CreateLesson createLesson=new CreateLesson(instructorManagment, instructorManagment.getCourseService(), instructor, courseId);

        createLesson.setVisible(true);
        createLesson.setLocationRelativeTo(null);
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
       String selected =jList1.getSelectedValue();
       if(selected==null)
       {
           JOptionPane.showMessageDialog(this,"Select a lesson.");
           return;
       }
      EditLesson e = new EditLesson(instructorManagment,instructor,courseId,selected);
       e.setVisible(true);
       e.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void quizAverageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizAverageBtnActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBoxLessons.getSelectedItem();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Select a lesson first!");
            return;
        }

        String lessonId = selected.split(" - ")[0];
        double average = instructorManagment.getLessonAverage(courseId, lessonId); 

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(average, "Average Score", lessonId);

        JFreeChart chart = ChartFactory.createBarChart(
                "Quiz Average for Lesson: " + lessonId,
                "Lesson",
                "Average Score",
                dataset
        );

        ChartPanel panel = new ChartPanel(chart);
        JFrame frame = new JFrame("Quiz Average");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(600, 400);
        frame.add(panel);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_quizAverageBtnActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        String selected=jList1.getSelectedValue();
         if(selected==null)
       {
           JOptionPane.showMessageDialog(this,"Select a lesson.");
           return;
       }
       boolean done=instructorManagment.deleteLesson(instructor, courseId, selected);
       if(done)
       {
           JOptionPane.showMessageDialog(this,"Lesson deleted successfully.");
           lessonList();
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Failed to delete lesson!");
       }
    }//GEN-LAST:event_button6ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        String selected =jList1.getSelectedValue();
       if(selected==null)
       {
           JOptionPane.showMessageDialog(this,"Select a lesson.");
           return;
       }
       Lesson lesson=instructorManagment.getCourseService().getLessonById(courseId, selected);
       if(lesson==null)
       {
           JOptionPane.showMessageDialog(this,"Lesson not found.");
           return;
       }
       if(lesson.getQuiz()!=null)
       {
           JOptionPane.showMessageDialog(this," Lesson has a Quiz.");
           return;
       }
       CreateQuiz createQuiz=new CreateQuiz(lesson,instructorManagment.getCourseService(),courseId,this);
       createQuiz.setVisible(true);
       createQuiz.setLocationRelativeTo(null); 
       this.setVisible(false);
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Button quizAverageBtn;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
