/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import JSON.CourseService;
import JSON.InstructorManagment;
import JSON.StudentService;
import Users.Instructor;
import Users.Student;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ViewStudentsPerformance extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentsPerformance
     */
   private InstructorManagment instructorManagment;
    private Instructor instructor;
    private CourseService courseService;
    private StudentService studentService;
    private String courseId;

    public ViewStudentsPerformance(InstructorManagment instructorManagment,
                                   Instructor instructor,
                                   CourseService courseService,
                                   StudentService studentService,
                                   String courseId) {

        this.instructorManagment = instructorManagment;
        this.instructor = instructor;
        this.courseService = courseService;
        this.studentService = studentService;
        this.courseId = courseId;

        initComponents();
        setupTable();
        loadStudentPerformance();
    }

    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Student ID");
        model.addColumn("Student Name");
        model.addColumn("Completed Lessons");
        model.addColumn("Average Quiz Score");

        studentsTable.setModel(model);
    }

   private void loadStudentPerformance() {
    DefaultTableModel model = (DefaultTableModel) studentsTable.getModel();
    model.setRowCount(0);

    // Get student IDs enrolled in the course
    List<String> studentIds = instructorManagment.getStudentsInCourse(courseId);

    if (studentIds == null || studentIds.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No students enrolled in this course.");
        return;
    }

    for (String studentId : studentIds) {

        // Convert studentId → Student object
        Student student = instructorManagment.getStudentService().getStudentById(studentId);

        if (student == null) {
            System.out.println("Warning: Student not found: " + studentId);
            continue;
        }

        // Get completed lessons count
        int completedLessons = instructorManagment.getStudentCompletedLessonsCount(studentId, courseId);

        // Get average quiz score
        double avgScore = instructorManagment.getStudentAverageQuizScore(studentId, courseId);

        // Add row to table
        model.addRow(new Object[]{
                student.getUserID(),
                student.getUserName(),
                completedLessons,
                avgScore
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        button4 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(studentsTable);

        button4.setLabel("back");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        InstructorDashboard d=new InstructorDashboard(instructorManagment,instructor);
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentsTable;
    // End of variables declaration//GEN-END:variables
}
