/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import Courses.Course;
import Courses.Lesson;
import JSON.CourseService;
import JSON.InstructorManagment;
import JSON.StudentService;
import Users.Instructor;
import Users.Student;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.plot.PlotOrientation;

/**
 *
 * @author HP
 */
public class ViewStudentsProgress extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentsProgress
     */
    private InstructorManagment instructorManagment;
    private Instructor instructor;
    private CourseService courseService;
    private StudentService studentService;
    private String courseId;
    
    
    public ViewStudentsProgress(InstructorManagment instructorManagment,Instructor instructor,CourseService courseService,StudentService studentService, String courseId) {
        this.courseService= courseService;
        this.studentService=studentService;
        this.courseId=courseId;
        this.instructorManagment= instructorManagment;
        this.instructor =instructor;
 initComponents();  

    jButton2.setText("View Chart");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
     public void actionPerformed(java.awt.event.ActionEvent evt) {
            viewChartBtnActionPerformed(evt);
        }
    });
        studentProgress();
    }
  
    private void studentProgress() {   
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[] { "ID", "Name", "Completion (%)" });

    ArrayList<String> students = courseService.getEnrolledStudents(courseId);

    for (String studentId : students) {   
        Student student = studentService.getStudentById(studentId);
        if (student != null) {
            double completion = instructorManagment.getStudentCourseCompletionPercentage(studentId, courseId);
            model.addRow(new Object[]{ student.getUserID(), student.getUserName(), String.format("%.1f%%", completion) });
        }
    }

    jTable1.setModel(model); // set the updated model
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("View Students Progress");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        scrollPane1.add(jScrollPane1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("view chart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InstructorDashboard d=new InstructorDashboard(instructorManagment,instructor);
        d.setVisible(true);
         d.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         viewChartBtnActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void viewChartBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
    int rowCount = jTable1.getRowCount();
    if (rowCount == 0) {
        JOptionPane.showMessageDialog(this, "No student progress to display!");
        return;
    }

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

   for (int i = 0; i < rowCount; i++) {
    String studentName = jTable1.getValueAt(i, 1).toString();
    String val = jTable1.getValueAt(i, 2).toString().replace("%", "");
    double completedPercent = Double.parseDouble(val);

    dataset.addValue(completedPercent, "Completion %", studentName);
}

JFreeChart chart = ChartFactory.createBarChart(
        "Progress for Course: " + courseId,
        "Student",        // Category axis (vertical)
        "Completion (%)", // Value axis (horizontal)
        dataset,
        PlotOrientation.HORIZONTAL, // Horizontal bars
        true,
        true,
        false
);

ChartPanel panel = new ChartPanel(chart);
JFrame frame = new JFrame("Student Progress Chart");
frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
frame.setSize(800, 600);
frame.add(panel);
frame.setLocationRelativeTo(null);
frame.setVisible(true);
}                                             


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
